
server:
  port: 8080



spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: 'false'


spring.output.ansi.enabled: ALWAYS
